"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from test1 import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ErrorInfoResponse:
    r"""ErrorInfo is returned by a handler in case of an error."""
    
    error: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('error') }})
    r"""An error details"""
    