"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import valuessecretsrequest as shared_valuessecretsrequest
from dataclasses_json import Undefined, dataclass_json
from test1 import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class PatchResourceDefinitionRequestRequest:
    r"""PatchResourceDefinitionRequest describes a ResourceDefinition change request."""
    
    driver_account: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('driver_account'), 'exclude': lambda f: f is None }})
    r"""(Optional) Security account required by the driver."""
    driver_inputs: Optional[shared_valuessecretsrequest.ValuesSecretsRequest] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('driver_inputs'), 'exclude': lambda f: f is None }})
    r"""ValuesSecrets stores data that should be passed around split by sensitivity."""
    name: Optional[str] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name'), 'exclude': lambda f: f is None }})
    r"""(Optional) Resource display name"""
    