"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class ValueSourceEnum(str, Enum):
    r"""Source of the value, \\"app\\" for app level, \\"env\\" for app env level."""
    APP = 'app'
    ENV = 'env'
