"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import environmenttyperesponse as shared_environmenttyperesponse
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from typing import Optional



@dataclasses.dataclass
class DeleteOrgsOrgIDEnvTypesEnvTypeIDRequest:
    env_type_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'envTypeId', 'style': 'simple', 'explode': False }})
    r"""ID of the Environment Type."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    




@dataclasses.dataclass
class DeleteOrgsOrgIDEnvTypesEnvTypeIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    delete_orgs_org_id_env_types_env_type_id_409_application_json_objects: Optional[list[dict[str, str]]] = dataclasses.field(default=None)
    r"""There are 1 or more Environments with this Type.
    
    To delete an Environment Type, there can be no Environments with that type in the Organization.
    """
    environment_type_response: Optional[shared_environmenttyperesponse.EnvironmentTypeResponse] = dataclasses.field(default=None)
    r"""The Environment Type requested."""
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""The Authorization header was not present or invalid."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

