"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from ..shared import resourcedefinitionchangeresponse as shared_resourcedefinitionchangeresponse
from typing import Optional



@dataclasses.dataclass
class DeleteOrgsOrgIDResourcesDefsDefIDCriteriaCriteriaIDRequest:
    criteria_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'criteriaId', 'style': 'simple', 'explode': False }})
    r"""The Matching Criteria ID."""
    def_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'defId', 'style': 'simple', 'explode': False }})
    r"""The Resource Definition ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    force: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'force', 'style': 'form', 'explode': True }})
    r"""If set to `true`, the Matching Criteria is deleted immediately, even if this action affects existing Active Resources."""
    




@dataclasses.dataclass
class DeleteOrgsOrgIDResourcesDefsDefIDCriteriaCriteriaIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    delete_orgs_org_id_resources_defs_def_id_criteria_criteria_id_404_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""The Resource Definition is not found."""
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""Internal application error."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    resource_definition_change_responses: Optional[list[shared_resourcedefinitionchangeresponse.ResourceDefinitionChangeResponse]] = dataclasses.field(default=None)
    r"""One or more Active Resources reference the Resource Definition through this Matching Criteria."""
    

