"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import deploymentresponse as shared_deploymentresponse
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from typing import Optional



@dataclasses.dataclass
class GetOrgsOrgIDAppsAppIDEnvsEnvIDDeploysDeployIDRequest:
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    deploy_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'deployId', 'style': 'simple', 'explode': False }})
    r"""The Deployment ID."""
    env_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'envId', 'style': 'simple', 'explode': False }})
    r"""The Environment ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    




@dataclasses.dataclass
class GetOrgsOrgIDAppsAppIDEnvsEnvIDDeploysDeployIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    deployment_response: Optional[shared_deploymentresponse.DeploymentResponse] = dataclasses.field(default=None)
    r"""The Deployment requested."""
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""No Deployment with `deployId` in Application and Environment."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

