"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from ..shared import resourcedefinitionresponse as shared_resourcedefinitionresponse
from typing import Optional



@dataclasses.dataclass
class GetOrgsOrgIDResourcesDefsRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    app: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'app', 'style': 'form', 'explode': True }})
    r"""(Optional) Filter Resource Definitions that may match a specific Application."""
    env: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'env', 'style': 'form', 'explode': True }})
    r"""(Optional) Filter Resource Definitions that may match a specific Environment."""
    env_type: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'env_type', 'style': 'form', 'explode': True }})
    r"""(Optional) Filter Resource Definitions that may match a specific Environment Type."""
    res: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'res', 'style': 'form', 'explode': True }})
    r"""(Optional) Filter Resource Definitions that may match a specific Resource."""
    res_type: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'res_type', 'style': 'form', 'explode': True }})
    r"""(Optional) Filter Resource Definitions that may match a specific Resource Type."""
    




@dataclasses.dataclass
class GetOrgsOrgIDResourcesDefsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""Internal application error."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    resource_definition_responses: Optional[list[shared_resourcedefinitionresponse.ResourceDefinitionResponse]] = dataclasses.field(default=None)
    r"""A possibly empty list of Resources Definitions."""
    

