"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import userprofileextendedresponse as shared_userprofileextendedresponse
from typing import Optional


@dataclasses.dataclass
class GetCurrentUserResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    user_profile_extended_response: Optional[shared_userprofileextendedresponse.UserProfileExtendedResponse] = dataclasses.field(default=None)
    r"""The extended user profile of the user."""
    