"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import valuesetversionresponse as shared_valuesetversionresponse
from typing import Optional



@dataclasses.dataclass
class GetOrgsOrgIDAppsAppIDEnvsEnvIDValueSetVersionsRequest:
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    env_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'envId', 'style': 'simple', 'explode': False }})
    r"""The Environment ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    key_changed: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'key_changed', 'style': 'form', 'explode': True }})
    r"""(Optional) Return only value set version where the specified key changed"""
    




@dataclasses.dataclass
class GetOrgsOrgIDAppsAppIDEnvsEnvIDValueSetVersionsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    value_set_version_responses: Optional[list[shared_valuesetversionresponse.ValueSetVersionResponse]] = dataclasses.field(default=None)
    r"""A possibly empty list of ValueSetVersion."""
    

