"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import eventresponse as shared_eventresponse
from typing import Optional



@dataclasses.dataclass
class GetOrgsOrgIDEventsRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    




@dataclasses.dataclass
class GetOrgsOrgIDEventsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    event_responses: Optional[list[shared_eventresponse.EventResponse]] = dataclasses.field(default=None)
    r"""A list of Events."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

