"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import environmentresponse as shared_environmentresponse
from typing import Optional


@dataclasses.dataclass
class GetOrgsOrgIDAppsAppIDEnvsRequest:
    
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    

@dataclasses.dataclass
class GetOrgsOrgIDAppsAppIDEnvsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    environment_responses: Optional[list[shared_environmentresponse.EnvironmentResponse]] = dataclasses.field(default=None)
    r"""A list of Environments associated with an Application."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    