"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import webhookresponse as shared_webhookresponse
from typing import Optional



@dataclasses.dataclass
class GetOrgsOrgIDAppsAppIDWebhooksRequest:
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    




@dataclasses.dataclass
class GetOrgsOrgIDAppsAppIDWebhooksResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    webhook_responses: Optional[list[shared_webhookresponse.WebhookResponse]] = dataclasses.field(default=None)
    r"""A list of Webhooks."""
    

