"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import imageresponse as shared_imageresponse
from typing import Optional


@dataclasses.dataclass
class GetOrgsOrgIDImagesRequest:
    
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The organization ID."""
    

@dataclasses.dataclass
class GetOrgsOrgIDImagesResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    image_responses: Optional[list[shared_imageresponse.ImageResponse]] = dataclasses.field(default=None)
    r"""Possibly empty list of Container Images."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    