"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from ..shared import resourceaccountresponse as shared_resourceaccountresponse
from typing import Optional



@dataclasses.dataclass
class GetOrgsOrgIDResourcesAccountsAccIDRequest:
    acc_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'accId', 'style': 'simple', 'explode': False }})
    r"""The Resource Account ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    




@dataclasses.dataclass
class GetOrgsOrgIDResourcesAccountsAccIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""A Resource Account with the 'accId' ID is not found or does not belong to the organization."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    resource_account_response: Optional[shared_resourceaccountresponse.ResourceAccountResponse] = dataclasses.field(default=None)
    r"""The requested Resources Account."""
    

