"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import deltarequest as shared_deltarequest
from ..shared import deltaresponse as shared_deltaresponse
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from typing import Optional


@dataclasses.dataclass
class PatchOrgsOrgIDAppsAppIDDeltasDeltaIDRequest:
    
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    delta_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'deltaId', 'style': 'simple', 'explode': False }})
    r"""ID of the Delta to update."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    request_body: list[shared_deltarequest.DeltaRequest] = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""An array of Deltas.
    
    The Deltas in the request are combined, meaning the current Delta is updated in turn by each Delta in the request. Once all Deltas have been combined, the resulting Delta is simplified.
    
    * All Modules in the `modules.add` property are replaced with the new Delta's values. If the value of a Module is `null`, and the ID is in the `modules.remove` list, it is removed from the `modules.remove` list.
    
    * All IDs listed in `modules.remove` are combined. Any ID in `modules.remove` and also in `modules.add` are removed from `modules.add`
    
    * The lists of JSON Patches in `modules.update` are concatenated or created in `modules.updates`.
    
    Simplification involves:
    
    * Applying any entries in `modules.updates` that have matching IDs in `modules.add` to the `modules.add` entry and removing the `modules.update` entry.
    
    * Reducing the number of JSON Patches in each `modules.update` entry to the smallest set that has the same effect.
    
    **Extension to JSON Patch**
    
    If a JSON Patch entry needs to be removed, without side effects, the `value` of the `remove` action can be set to `{\"scope\": \"delta\"}. This will result in the remove action being used during simplification but be discarded before the Delta is finalized.
    
    If the user making the request is not the user who created the Delta and they are not already on the contributors list, they will be added to the contributors list.
    
    _NOTE: If the `id` or `metadata` properties are specified, they will be ignored._
    """
    

@dataclasses.dataclass
class PatchOrgsOrgIDAppsAppIDDeltasDeltaIDResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    delta_response: Optional[shared_deltaresponse.DeltaResponse] = dataclasses.field(default=None)
    r"""The requested Deployment Delta."""
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""The request was invalid."""
    patch_orgs_org_id_apps_app_id_deltas_delta_id_404_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""No Deployment Delta with ID `deltaId` found in Application."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    