"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from ..shared import valuepatchpayloadrequest as shared_valuepatchpayloadrequest
from ..shared import valueresponse as shared_valueresponse
from typing import Optional



@dataclasses.dataclass
class PatchOrgsOrgIDAppsAppIDEnvsEnvIDValuesKeyRequest:
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    env_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'envId', 'style': 'simple', 'explode': False }})
    r"""The Environment ID."""
    key: str = dataclasses.field(metadata={'path_param': { 'field_name': 'key', 'style': 'simple', 'explode': False }})
    r"""The key to update."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    value_patch_payload_request: shared_valuepatchpayloadrequest.ValuePatchPayloadRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""At least `value` or `description` must be supplied. All other fields will be ignored."""
    




@dataclasses.dataclass
class PatchOrgsOrgIDAppsAppIDEnvsEnvIDValuesKeyResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""Input not valid."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    value_response: Optional[shared_valueresponse.ValueResponse] = dataclasses.field(default=None)
    r"""Shared Value successfully updated."""
    

