"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from ..shared import patchresourcedefinitionrequestrequest as shared_patchresourcedefinitionrequestrequest
from ..shared import resourcedefinitionresponse as shared_resourcedefinitionresponse
from typing import Optional



@dataclasses.dataclass
class PatchOrgsOrgIDResourcesDefsDefIDRequest:
    def_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'defId', 'style': 'simple', 'explode': False }})
    r"""The Resource Definition ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    patch_resource_definition_request_request: shared_patchresourcedefinitionrequestrequest.PatchResourceDefinitionRequestRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""The Resource Definition record details.
    
    The PATCH operation would change the value of the property if it is included in the request payload JSON, and not `null`. Missing and `null` properties are ignored.
    
    For the map properties, such as PatchResourceDefinitionRequest.DriverInputs, the merge operation is applied.
    
    Merge rules are as follows:
    
    - If a map property has a value, it is replaced (or added).
    
    - If a map property is set to `null`, it is removed.
    
    - If a map property is not included (missing in JSON), it remains unchanged.
    """
    




@dataclasses.dataclass
class PatchOrgsOrgIDResourcesDefsDefIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""One or more request parameters is missing or invalid."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    resource_definition_response: Optional[shared_resourcedefinitionresponse.ResourceDefinitionResponse] = dataclasses.field(default=None)
    r"""The updated Resource Definition."""
    

