"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import deltarequest as shared_deltarequest
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from typing import Any, Optional



@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDDeltasRequest:
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    delta_request: shared_deltarequest.DeltaRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""A Deployment Delta to create.
    
    The Deployment Delta will be added with the provided content of `modules` and the 'env_id' and 'name' properties of the 'metadata' property.
    
    NOTE: If the `id` property is specified, it will be ignored. A new ID will be generated and returned in the response.
    """
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    




@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDDeltasResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""The request was invalid."""
    post_orgs_org_id_apps_app_id_deltas_200_application_json_one_of: Optional[Any] = dataclasses.field(default=None)
    r"""The requested Deployment Delta."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

