"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import deltarequest as shared_deltarequest
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from typing import Optional



@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDSetsSetIDRequest:
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    delta_request: shared_deltarequest.DeltaRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""The Delta to apply to the Set.
    
    NOTE: The `id` parameter is ignored if provided. The request body should be the full Delta.
    """
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    set_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'setId', 'style': 'simple', 'explode': False }})
    r"""ID of the Deployment Set."""
    




@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDSetsSetIDResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""Deployment Delta is incompatible with the Deployment Set specified by `setId`."""
    post_orgs_org_id_apps_app_id_sets_set_id_200_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""A Deployment Delta which if applied to the Set with ID `sourceSetId` gives the Set with ID `setId`."""
    post_orgs_org_id_apps_app_id_sets_set_id_404_application_json_string: Optional[str] = dataclasses.field(default=None)
    r"""No Deployment Set with ID `setId` found in Application."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

