"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import applicationcreationrequest as shared_applicationcreationrequest
from ..shared import applicationresponse as shared_applicationresponse
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from typing import Optional


@dataclasses.dataclass
class PostOrgsOrgIDAppsRequest:
    
    application_creation_request: shared_applicationcreationrequest.ApplicationCreationRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""The request ID, Human-friendly name and environment of the Application."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    

@dataclasses.dataclass
class PostOrgsOrgIDAppsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    application_response: Optional[shared_applicationresponse.ApplicationResponse] = dataclasses.field(default=None)
    r"""The Application requested."""
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""The request body was unparseable."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    