"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import environmentdefinitionrequest as shared_environmentdefinitionrequest
from ..shared import environmentresponse as shared_environmentresponse
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from typing import Optional


@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDEnvsRequest:
    
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    environment_definition_request: shared_environmentdefinitionrequest.EnvironmentDefinitionRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""The ID, Name, Type, and Deployment the Environment will be derived from."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    

@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDEnvsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    environment_response: Optional[shared_environmentresponse.EnvironmentResponse] = dataclasses.field(default=None)
    r"""The new Environment."""
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""The supplied `id` is an invalid ID or a required field is missing."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    