"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from ..shared import matchingcriteriaresponse as shared_matchingcriteriaresponse
from ..shared import matchingcriteriarulerequest as shared_matchingcriteriarulerequest
from typing import Optional



@dataclasses.dataclass
class PostOrgsOrgIDResourcesDefsDefIDCriteriaRequest:
    def_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'defId', 'style': 'simple', 'explode': False }})
    r"""The Resource Definition ID."""
    matching_criteria_rule_request: shared_matchingcriteriarulerequest.MatchingCriteriaRuleRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""Matching Criteria rules."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    




@dataclasses.dataclass
class PostOrgsOrgIDResourcesDefsDefIDCriteriaResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""One or more request parameters is missing or invalid."""
    matching_criteria_response: Optional[shared_matchingcriteriaresponse.MatchingCriteriaResponse] = dataclasses.field(default=None)
    r"""The newly added Matching Criteria details."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

