"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import errorinforesponse as shared_errorinforesponse
from ..shared import webhookrequest as shared_webhookrequest
from ..shared import webhookresponse as shared_webhookresponse
from typing import Optional



@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDWebhooksRequest:
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    webhook_request: shared_webhookrequest.WebhookRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDWebhooksResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    error_info_response: Optional[shared_errorinforesponse.ErrorInfoResponse] = dataclasses.field(default=None)
    r"""Some of the values supplied are invalid."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    webhook_response: Optional[shared_webhookresponse.WebhookResponse] = dataclasses.field(default=None)
    r"""A created webhook."""
    

