"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from . import utils
from test1.models import operations, shared
from typing import Optional

class ResourceAccount:
    r"""ResourceAccount represents the account being used to access a resource.
    
    Resource Accounts hold credentials that are required to provision and manage resources.
    <SchemaDefinition schemaRef=\"#/components/schemas/ResourceAccountRequest\" />
    """
    _client: requests_http.Session
    _security_client: requests_http.Session
    _server_url: str
    _language: str
    _sdk_version: str
    _gen_version: str

    def __init__(self, client: requests_http.Session, security_client: requests_http.Session, server_url: str, language: str, sdk_version: str, gen_version: str) -> None:
        self._client = client
        self._security_client = security_client
        self._server_url = server_url
        self._language = language
        self._sdk_version = sdk_version
        self._gen_version = gen_version
        
    
    def get_orgs_org_id_resources_accounts(self, request: operations.GetOrgsOrgIDResourcesAccountsRequest) -> operations.GetOrgsOrgIDResourcesAccountsResponse:
        r"""List Resource Accounts in the organization."""
        base_url = self._server_url
        
        url = utils.generate_url(operations.GetOrgsOrgIDResourcesAccountsRequest, base_url, '/orgs/{orgId}/resources/accounts', request)
        
        
        client = self._client
        
        http_res = client.request('GET', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.GetOrgsOrgIDResourcesAccountsResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[list[shared.ResourceAccountResponse]])
                res.resource_account_responses = out
        elif http_res.status_code == 500:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.HumanitecErrorResponse])
                res.humanitec_error_response = out

        return res

    
    def get_orgs_org_id_resources_accounts_acc_id_(self, request: operations.GetOrgsOrgIDResourcesAccountsAccIDRequest) -> operations.GetOrgsOrgIDResourcesAccountsAccIDResponse:
        r"""Get a Resource Account."""
        base_url = self._server_url
        
        url = utils.generate_url(operations.GetOrgsOrgIDResourcesAccountsAccIDRequest, base_url, '/orgs/{orgId}/resources/accounts/{accId}', request)
        
        
        client = self._client
        
        http_res = client.request('GET', url)
        content_type = http_res.headers.get('Content-Type')

        res = operations.GetOrgsOrgIDResourcesAccountsAccIDResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ResourceAccountResponse])
                res.resource_account_response = out
        elif http_res.status_code in [404, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.HumanitecErrorResponse])
                res.humanitec_error_response = out

        return res

    
    def patch_orgs_org_id_resources_accounts_acc_id_(self, request: operations.PatchOrgsOrgIDResourcesAccountsAccIDRequest) -> operations.PatchOrgsOrgIDResourcesAccountsAccIDResponse:
        r"""Update a Resource Account."""
        base_url = self._server_url
        
        url = utils.generate_url(operations.PatchOrgsOrgIDResourcesAccountsAccIDRequest, base_url, '/orgs/{orgId}/resources/accounts/{accId}', request)
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "update_resource_account_request_request", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = self._client
        
        http_res = client.request('PATCH', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.PatchOrgsOrgIDResourcesAccountsAccIDResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ResourceAccountResponse])
                res.resource_account_response = out
        elif http_res.status_code in [400, 404, 422, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.HumanitecErrorResponse])
                res.humanitec_error_response = out

        return res

    
    def post_orgs_org_id_resources_accounts(self, request: operations.PostOrgsOrgIDResourcesAccountsRequest) -> operations.PostOrgsOrgIDResourcesAccountsResponse:
        r"""Create a new Resource Account in the organization."""
        base_url = self._server_url
        
        url = utils.generate_url(operations.PostOrgsOrgIDResourcesAccountsRequest, base_url, '/orgs/{orgId}/resources/accounts', request)
        
        headers = {}
        req_content_type, data, form = utils.serialize_request_body(request, "create_resource_account_request_request", 'json')
        if req_content_type not in ('multipart/form-data', 'multipart/mixed'):
            headers['content-type'] = req_content_type
        if data is None and form is None:
            raise Exception('request body is required')
        
        client = self._client
        
        http_res = client.request('POST', url, data=data, files=form, headers=headers)
        content_type = http_res.headers.get('Content-Type')

        res = operations.PostOrgsOrgIDResourcesAccountsResponse(status_code=http_res.status_code, content_type=content_type, raw_response=http_res)
        
        if http_res.status_code == 200:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.ResourceAccountResponse])
                res.resource_account_response = out
        elif http_res.status_code in [400, 401, 409, 422, 500]:
            if utils.match_content_type(content_type, 'application/json'):
                out = utils.unmarshal_json(http_res.text, Optional[shared.HumanitecErrorResponse])
                res.humanitec_error_response = out

        return res

    