"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from ..shared import resourcedefinitionchangeresponse as shared_resourcedefinitionchangeresponse
from typing import Optional


@dataclasses.dataclass
class DeleteOrgsOrgIDResourcesDefsDefIDRequest:
    
    def_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'defId', 'style': 'simple', 'explode': False }})
    r"""The Resource Definition ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    force: Optional[bool] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'force', 'style': 'form', 'explode': True }})
    r"""If set to `true`, will mark the Resource Definition for deletion, even if it affects existing Active Resources."""
    

@dataclasses.dataclass
class DeleteOrgsOrgIDResourcesDefsDefIDResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""A Resource Driver with the 'driverId' ID is not found or is not accessible by the organization."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    resource_definition_change_responses: Optional[list[shared_resourcedefinitionchangeresponse.ResourceDefinitionChangeResponse]] = dataclasses.field(default=None)
    r"""List of Active Resources that still reference this Resource Definition."""
    