"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import errorinforesponse as shared_errorinforesponse
from ..shared import organizationresponse as shared_organizationresponse
from typing import Optional


@dataclasses.dataclass
class GetOrgsOrgIDRequest:
    
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    

@dataclasses.dataclass
class GetOrgsOrgIDResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    error_info_response: Optional[shared_errorinforesponse.ErrorInfoResponse] = dataclasses.field(default=None)
    r"""Invalid request parameters or payload. E.g. invalid `orgId` format."""
    organization_response: Optional[shared_organizationresponse.OrganizationResponse] = dataclasses.field(default=None)
    r"""Returns organization details."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    