"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import organizationresponse as shared_organizationresponse
from typing import Optional


@dataclasses.dataclass
class GetOrgsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    organization_responses: Optional[list[shared_organizationresponse.OrganizationResponse]] = dataclasses.field(default=None)
    r"""A list of available organizations (based on the current user access level)."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    