"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import automationrulerequest as shared_automationrulerequest
from ..shared import automationruleresponse as shared_automationruleresponse
from ..shared import errorinforesponse as shared_errorinforesponse
from typing import Optional


@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDEnvsEnvIDRulesRequest:
    
    app_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'appId', 'style': 'simple', 'explode': False }})
    r"""The Application ID."""
    automation_rule_request: shared_automationrulerequest.AutomationRuleRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    r"""The definition of the Automation Rule."""
    env_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'envId', 'style': 'simple', 'explode': False }})
    r"""The Environment ID."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    

@dataclasses.dataclass
class PostOrgsOrgIDAppsAppIDEnvsEnvIDRulesResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    automation_rule_response: Optional[shared_automationruleresponse.AutomationRuleResponse] = dataclasses.field(default=None)
    r"""The AutomationRule"""
    error_info_response: Optional[shared_errorinforesponse.ErrorInfoResponse] = dataclasses.field(default=None)
    r"""The input was not a valid Automation Rule."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    