"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import createresourceaccountrequestrequest as shared_createresourceaccountrequestrequest
from ..shared import humanitecerrorresponse as shared_humanitecerrorresponse
from ..shared import resourceaccountresponse as shared_resourceaccountresponse
from typing import Optional


@dataclasses.dataclass
class PostOrgsOrgIDResourcesAccountsRequest:
    
    create_resource_account_request_request: shared_createresourceaccountrequestrequest.CreateResourceAccountRequestRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'orgId', 'style': 'simple', 'explode': False }})
    r"""The Organization ID."""
    

@dataclasses.dataclass
class PostOrgsOrgIDResourcesAccountsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    humanitec_error_response: Optional[shared_humanitecerrorresponse.HumanitecErrorResponse] = dataclasses.field(default=None)
    r"""One or more request parameters is missing or invalid."""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    resource_account_response: Optional[shared_resourceaccountresponse.ResourceAccountResponse] = dataclasses.field(default=None)
    r"""The newly created Resources Account details."""
    