"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import environmentbaseresponse as shared_environmentbaseresponse
from dataclasses_json import Undefined, dataclass_json
from test_1 import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ApplicationResponse:
    r"""An Application is a collection of Workloads that work together. When deployed, all Workloads in an Application are deployed to the same namespace.
    
    Apps are the root of the configuration tree holding Environments, Deployments, Shared Values, and Secrets.
    """
    created_at: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('created_at') }})
    r"""The timestamp in UTC indicates when the Application was created."""
    created_by: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('created_by') }})
    r"""The user who created the Application."""
    envs: list[shared_environmentbaseresponse.EnvironmentBaseResponse] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('envs') }})
    r"""The Environments associated with the Application."""
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""The ID which refers to a specific application."""
    name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('name') }})
    r"""The Human-friendly name for the Application."""
    

