"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from test_1 import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class AutomationRuleResponse:
    r"""An Automation Rule defining how and when artefacts in an environment should be updated."""
    
    active: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('active') }})
    r"""Whether the rule will be processed or not."""
    artefacts_filter: list[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('artefacts_filter') }})
    r"""A list of artefact names to be processed by the rule. If the array is empty, it implies include all. If `exclude_artefacts_filter` is true, this list describes the artefacts to exclude."""
    created_at: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('created_at') }})
    r"""The timestamp in UTC of when the Automation Rule was created."""
    exclude_artefacts_filter: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('exclude_artefacts_filter') }})
    r"""Whether the artefacts specified in `artefacts_filter` should be excluded (true) or included (false) in the automation rule."""
    exclude_images_filter: bool = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('exclude_images_filter') }})
    r"""DEPRECATED: Whether the images specified in `images_filter` should be excluded (true) or included (false) in the automation rule."""
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""The unique ID for this rule."""
    images_filter: list[str] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('images_filter') }})
    r"""DEPRECATED: A list of image IDs to be processed by the rule. If the array is empty, it implies include all. If `exclude_images_filter` is true, this list describes images to exclude."""
    match: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('match') }})
    r"""DEPRECATED: A regular expression applied to the branch or tag name depending on the value of `update_to`. Defaults to match all if omitted or empty."""
    match_ref: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('match_ref') }})
    r"""A regular expression applied to the ref of a new artefact version. Defaults to match all if omitted or empty."""
    type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""Specifies the type of event. Currently, only updates to either branches or tags are supported. Must be `\\"update\\"`."""
    update_to: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('update_to') }})
    r"""DEPRECATED: Specifies whether the update occurs on commit to branch or creation of tag. Must be one of `\\"branch\\"` or `\\"tag\\"`."""
    updated_at: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('updated_at') }})
    r"""The timestamp in UTC of when the Automation Rule was updated."""
    