"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from test_1 import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class EnvironmentTypeResponse:
    r"""Environment Types are a way of grouping and managing Environments. Every Environment has exactly 1 Environment Type.
    
    Environment Types can be used with External Resources to manage where resources such as databases are provisioned or even which cluster to deploy to.
    """
    description: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('description') }})
    r"""A Human-readable description of the Environment Type"""
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""The ID of the Environment Type. (Must be unique within an Organization.)"""
    

