"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import accountcredsrequest as shared_accountcredsrequest
from ..shared import clustersecretrequest as shared_clustersecretrequest
from dataclasses_json import Undefined, dataclass_json
from test_1 import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RegistryRequest:
    r"""Humanitec can be used to manage registry credentials. The Registry object represents how to match credentials to a particular registry.
    
    Humanitec supports all Docker compatible registries as well as the custom authentication formats used by AWS Elastic Container Registry and Google Container Registry. It also supports the injection of a specific secret to be copied from an existing namespace in the cluster.
    """
    
    id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('id') }})
    r"""Registry ID, unique within the Organization."""
    registry: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('registry') }})
    r"""Registry name, usually in a \\"{domain}\\" or \\"{domain}/{project}\\" format."""
    type: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('type') }})
    r"""Registry type, describes the registry authentication method, and defines the schema for the credentials.
    
    Supported values:
    
    - `public`
    
    - `basic`
    
    - `google_gcr`
    
    - `amazon_ecr`
    
    - `secret_ref`
    """
    creds: Optional[shared_accountcredsrequest.AccountCredsRequest] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('creds'), 'exclude': lambda f: f is None }})
    r"""AccountCreds represents an account credentials (either, username- or token-based)."""
    enable_ci: Optional[bool] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('enable_ci'), 'exclude': lambda f: f is None }})
    r"""Indicates if registry secrets and credentials should be exposed to CI agents."""
    secrets: Optional[dict[str, shared_clustersecretrequest.ClusterSecretRequest]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('secrets'), 'exclude': lambda f: f is None }})
    r"""ClusterSecretsMap stores a list of Kuberenetes secret references for the target deployment clusters."""
    