"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from test_1 import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ResourceDefinitionChangeResponse:
    r"""ResourceDefinitionChange describes the effects of a Resource Definition or Matching Criteria update/deletion."""
    app_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('app_id') }})
    r"""The ID of the App the resource is associated with."""
    env_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('env_id') }})
    r"""The ID of the Environment the resource is associated with."""
    from_def: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('from_def') }})
    r"""The Resource Definition that this resource was provisioned from."""
    res_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('res_id') }})
    r"""The ID of the resource"""
    to_def: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('to_def') }})
    r"""The Resource Definition that resource *will be* provisioned from if the change is applied."""
    

